name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run Tests
        run: |
          echo "Tests passed!"  # (replace later with pytest if needed)

      - name: Zip Lambda code
        run: |
          cd src
          zip -r ../lambda.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: lambda.zip
