name: Performance Tests

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Locust performance test
        env:
          LAMBDA_URL: ${{ secrets.LAMBDA_URL }}
        run: |
          locust -f locustfile.py --headless -u 10 -r 2 -t 1m --host $LAMBDA_URL
